## NumPy

In [1]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]


'1.15.0'

In [2]:
# Criando um array NumPy
array1 = np.arange(15)

In [3]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
# Help
?array1

In [5]:
array1.mean()

7.0

In [6]:
array1.sum()

105

In [7]:
array1.min()

0

In [8]:
array1.max()

14

In [9]:
array1.std()

4.320493798938574

## Utilizando List Comprehensions em Arrays NumPy

In [10]:
[x * x for x in array1]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [11]:
[x * x for x in array1 if x % 2 == 0]

[0, 4, 16, 36, 64, 100, 144, 196]

## Utilizando Função Lambda em Arrays NumPy

In [12]:
list(filter(lambda x: x%2==0, array1))

[0, 2, 4, 6, 8, 10, 12, 14]

In [13]:
# Atenção com a notação
array1%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [15]:
## Atenção com a notação
array1[array1%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

## Avaliando a Performance

In [17]:
# Performance usando list comprehension
%timeit [x for x in array1 if x%2==0]

10.2 µs ± 1.83 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [18]:
# Performance usando NumPy
%timeit array1[array1%2==0]

4.46 µs ± 391 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Usando Operadores Lógicos

In [19]:
array1 > 8

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True])

In [21]:
array1[array1>8]

array([ 9, 10, 11, 12, 13, 14])

In [22]:
# Operador lógico and
(array1 > 9) & (array1 < 12)

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True, False, False, False])

In [23]:
# Operador lógico or
(array1 > 13) | (array1 < 12)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True])

In [24]:
# Criando um array NumPy com list comprehension
array2 = np.array([x**3 for x in range(15)])

In [28]:
array2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [29]:
array2 = np.array([True for x in range(15)])

In [30]:
array2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [31]:
# Usando um array como índice para outro array
array1[array2]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])