In [1]:
import numpy as np

## Criando Matrizes

In [2]:
mat1 = np.matrix('1,2,3; 4,5,6')

In [3]:
print(mat1)

[[1 2 3]
 [4 5 6]]


In [4]:
type(mat1)

numpy.matrixlib.defmatrix.matrix

In [5]:
mat2 = np.matrix([[1,2,3],[4,5,6]])
print(mat2)

[[1 2 3]
 [4 5 6]]


In [6]:
mat3 = np.matrix([[0,10,0,0,0],
                  [0,0,20,0,0],
                  [0,0,0,30,0],
                  [0,0,0,0,40],
                  [0,0,0,0,0]])
print(mat3)

[[ 0 10  0  0  0]
 [ 0  0 20  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 40]
 [ 0  0  0  0  0]]


In [8]:
mat3[2,3]

30

## Matriz Esparsa

In [9]:
import scipy.sparse

In [10]:
linhas = np.array([0,1,2,3])
colunas = np.array([1,2,3,4])
valores = np.array([10,20,30,40])

In [11]:
mat4 = scipy.sparse.coo_matrix((valores, (linhas, colunas)))
print(mat4)

  (0, 1)	10
  (1, 2)	20
  (2, 3)	30
  (3, 4)	40


In [12]:
print(mat4.todense())

[[ 0 10  0  0  0]
 [ 0  0 20  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 40]]


In [13]:
scipy.sparse.isspmatrix_coo(mat4)

True

## Operações com arrays e matrizes

In [14]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [15]:
a*a

array([[ 1,  4],
       [ 9, 16]])

In [16]:
A = np.mat(a)
A

matrix([[1, 2],
        [3, 4]])

In [17]:
A*A

matrix([[ 7, 10],
        [15, 22]])

In [18]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [19]:
mat5 = np.asmatrix(a)

In [20]:
mat5

matrix([[1, 2],
        [3, 4]])

In [21]:
mat5*mat5

matrix([[ 7, 10],
        [15, 22]])

In [22]:
array2 = np.asarray(mat5)

In [23]:
array2

array([[1, 2],
       [3, 4]])

In [24]:
array2*array2

array([[ 1,  4],
       [ 9, 16]])